version: '3.8'
services:
  api:
    build: .
    container_name: clodure_oriented_api
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/clodure_db
    depends_on:
      - db
    ports:
      - "3030:3030"
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: clodure_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: clodure_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
