[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.195", features = ["derive"] }
uuid = { version = "1.6.1", features = ["v4", "serde"] }
thiserror = "2.0.12"
